# Generated by Django 2.1.15 on 2020-06-16 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Rank', models.IntegerField()),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_comments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=50)),
                ('Audience_score', models.FloatField()),
                ('country', models.CharField(max_length=20)),
                ('Release_date', models.CharField(max_length=20)),
                ('Showtimes', models.CharField(max_length=10)),
                ('movie_director', models.CharField(max_length=10)),
                ('Actors', models.CharField(max_length=50)),
                ('Rating', models.CharField(max_length=15)),
                ('imgUrl', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('heart', models.IntegerField()),
                ('Screening', models.CharField(max_length=10)),
                ('people', models.IntegerField()),
                ('attendance', models.CharField(max_length=30)),
                ('still_img', models.CharField(max_length=150)),
                ('like_users', models.ManyToManyField(blank=True, related_name='like_movies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=5)),
                ('drama', models.BooleanField(default=False)),
                ('fear', models.BooleanField(default=False)),
                ('melloh', models.BooleanField(default=False)),
                ('thriller', models.BooleanField(default=False)),
                ('comedey', models.BooleanField(default=False)),
                ('animation', models.BooleanField(default=False)),
                ('suspense', models.BooleanField(default=False)),
                ('action', models.BooleanField(default=False)),
                ('sf', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('kids', models.BooleanField(default=False)),
                ('parent_F', models.IntegerField()),
                ('parent_M', models.IntegerField()),
                ('Favorite', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Movie'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
